[[Robotframework-component]]
== Robotframework Component

*Available as of Camel version 3.0.0*

The *robotframework:* component allows for processing camel exchanges
in acceptence test suites which are already implemented with its own DSL. 
The depending keyword libraries that can be used inside test suites 
implemented in Robot DSL, could have been implemented either via 
Java or Pyhton.

This component will let you execute business logic of acceptence test cases 
in Robot language on which you can pass parameters to feed data via power 
of Camel Routes, however there is no reverse binding of parameters back where
you can pass values into Camel exchange. Therefore, for that reason, it actually
acts like a template language having camel exchange binding in the test cases 
implemented. 

[source,xml]
-------------------------------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-robotframework</artifactId>
    <version>x.x.x</version> <!-- use the same version as your Camel core version -->
</dependency>
-------------------------------------------------------------------------------------

### URI format

[source,java]
-------------------------------
robotframework:templateName[?options]
-------------------------------

Where *templateName* is the classpath-local URI of the template to
invoke; or the complete URL of the remote template (eg:
\file://folder/myfile.robot).

You can append query options to the URI in the following format,
`?option=value&option=value&...`

### Options

// component options: START


// component options: END


// endpoint options: START

The Robotframework endpoint is configured using URI syntax:

----
robotframework:resourceUri
----

with the following path and query parameters:

// endpoint options: END
// spring-boot-auto-configure options: START
=== Spring Boot Auto-Configuration

When using Spring Boot make sure to use the following Maven dependency to have support for auto configuration:

[source,xml]
----
<dependency>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-robotframework-starter</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel core version -->
</dependency>
----

// spring-boot-auto-configure options: END


### Samples

For example you could use something like:

[source,java]
-------------------------------------------
from("activemq:My.Queue").
  to("freemarker:com/acme/MyResponse.ftl");
-------------------------------------------

To use a FreeMarker template to formulate a response for a message for
InOut message exchanges (where there is a `JMSReplyTo` header).

If you want to use InOnly and consume the message and send it to another
destination you could use:

[source,java]
-------------------------------------------
from("activemq:My.Queue").
  to("freemarker:com/acme/MyResponse.ftl").
  to("activemq:Another.Queue");
-------------------------------------------

And to disable the content cache, e.g. for development usage where the
`.ftl` template should be hot reloaded:

[source,java]
--------------------------------------------------------------
from("activemq:My.Queue").
  to("freemarker:com/acme/MyResponse.ftl?contentCache=false").
  to("activemq:Another.Queue");
--------------------------------------------------------------

And a file-based resource:

[source,java]
---------------------------------------------------------------------
from("activemq:My.Queue").
  to("freemarker:file://myfolder/MyResponse.ftl?contentCache=false").
  to("activemq:Another.Queue");
---------------------------------------------------------------------

It's possible to specify what template the component
should use dynamically via a header, so for example:

[source,java]
---------------------------------------------------------------------------------------------
from("direct:in").
  setHeader(FreemarkerConstants.FREEMARKER_RESOURCE_URI).constant("path/to/my/template.ftl").
  to("freemarker:dummy");
---------------------------------------------------------------------------------------------


### See Also

* Configuring Camel
* Component
* Endpoint
* Getting Started